global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker_host'
    # This assumes we will run a "node-exporter" container to read system stats
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'airflow'
    # Airflow metrics (if configured) usually expose on a stats endpoint
    static_configs:
      - targets: ['airflow-webserver:8080']